USE [master]
GO
/****** Object:  Database [API_Kinhmat]    Script Date: 13/12/2024 7:04:26 CH ******/
CREATE DATABASE [API_Kinhmat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'API_Kinhmat', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\API_Kinhmat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'API_Kinhmat_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\API_Kinhmat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [API_Kinhmat] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [API_Kinhmat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [API_Kinhmat] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [API_Kinhmat] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [API_Kinhmat] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [API_Kinhmat] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [API_Kinhmat] SET ARITHABORT OFF 
GO
ALTER DATABASE [API_Kinhmat] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [API_Kinhmat] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [API_Kinhmat] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [API_Kinhmat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [API_Kinhmat] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [API_Kinhmat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [API_Kinhmat] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [API_Kinhmat] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [API_Kinhmat] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [API_Kinhmat] SET  DISABLE_BROKER 
GO
ALTER DATABASE [API_Kinhmat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [API_Kinhmat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [API_Kinhmat] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [API_Kinhmat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [API_Kinhmat] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [API_Kinhmat] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [API_Kinhmat] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [API_Kinhmat] SET RECOVERY FULL 
GO
ALTER DATABASE [API_Kinhmat] SET  MULTI_USER 
GO
ALTER DATABASE [API_Kinhmat] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [API_Kinhmat] SET DB_CHAINING OFF 
GO
ALTER DATABASE [API_Kinhmat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [API_Kinhmat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [API_Kinhmat] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [API_Kinhmat] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'API_Kinhmat', N'ON'
GO
ALTER DATABASE [API_Kinhmat] SET QUERY_STORE = ON
GO
ALTER DATABASE [API_Kinhmat] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [API_Kinhmat]
GO
/****** Object:  Table [dbo].[Danhmuc]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Danhmuc](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[danhmuc] [nvarchar](50) NULL,
	[mota] [nvarchar](50) NULL,
 CONSTRAINT [PK_Danhmuc] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Donhang]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Donhang](
	[mahd] [int] IDENTITY(1,1) NOT NULL,
	[iduser] [int] NULL,
	[ten] [nvarchar](50) NULL,
	[sdt] [nvarchar](50) NULL,
	[email] [nvarchar](50) NULL,
	[diachi] [nvarchar](50) NULL,
	[ghichu] [nvarchar](200) NULL,
	[thoigian] [datetime] NULL,
	[tongtien] [int] NULL,
	[trangthai] [int] NULL,
 CONSTRAINT [PK_Donhang] PRIMARY KEY CLUSTERED 
(
	[mahd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DonhangChitiet]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonhangChitiet](
	[macthd] [int] IDENTITY(1,1) NOT NULL,
	[mahd] [int] NULL,
	[maSKU] [int] NULL,
	[soluong] [int] NULL,
	[giaban] [int] NULL,
	[mausac] [nvarchar](50) NULL,
 CONSTRAINT [PK_DonhangChitiet] PRIMARY KEY CLUSTERED 
(
	[macthd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kinhmat]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kinhmat](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ten] [nvarchar](50) NULL,
	[soluong] [int] NULL,
	[madanhmuc] [int] NULL,
	[thuonghieu] [nvarchar](50) NULL,
	[xuatxu] [nvarchar](50) NULL,
	[chatlieu] [nvarchar](50) NULL,
	[kieudang] [nvarchar](50) NULL,
	[mota] [nvarchar](50) NULL,
	[anh] [nvarchar](50) NULL,
	[trangthai] [int] NULL,
 CONSTRAINT [PK_Kinhmat] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KinhmatSKU]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KinhmatSKU](
	[idSKU] [int] IDENTITY(1,1) NOT NULL,
	[masp] [int] NULL,
	[soluong] [int] NULL,
	[gianhap] [int] NULL,
	[giaban] [int] NULL,
	[mausac] [nvarchar](50) NULL,
	[anh] [nvarchar](50) NULL,
	[trangthai] [int] NULL,
 CONSTRAINT [PK_KinhmatSKU] PRIMARY KEY CLUSTERED 
(
	[idSKU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Nguoidung]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Nguoidung](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NULL,
	[pass] [varchar](50) NULL,
	[ten] [nvarchar](50) NULL,
	[sdt] [nvarchar](50) NULL,
	[email] [nvarchar](50) NULL,
	[trangthai] [int] NULL,
 CONSTRAINT [PK_Nguoidung] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Thanhtoan]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Thanhtoan](
	[mathanhtoan] [int] IDENTITY(1,1) NOT NULL,
	[mahd] [int] NULL,
	[phuongthucthanhtoan] [int] NULL,
	[ngaythanhtoan] [datetime] NULL,
	[tongtien] [int] NULL,
	[trangthai] [int] NULL,
 CONSTRAINT [PK_Thanhtoan] PRIMARY KEY CLUSTERED 
(
	[mathanhtoan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Thongtinvanchuyen]    Script Date: 13/12/2024 7:04:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Thongtinvanchuyen](
	[mavandon] [nvarchar](50) NOT NULL,
	[mahd] [int] NULL,
	[donvivanchuyen] [nvarchar](50) NULL,
	[ngaygiao] [datetime] NULL,
	[ngaynhan] [nvarchar](50) NULL,
	[trangthai] [int] NULL,
 CONSTRAINT [PK_Thongtinvanchuyen] PRIMARY KEY CLUSTERED 
(
	[mavandon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Donhang]  WITH CHECK ADD  CONSTRAINT [FK_Donhang_Nguoidung] FOREIGN KEY([iduser])
REFERENCES [dbo].[Nguoidung] ([id])
GO
ALTER TABLE [dbo].[Donhang] CHECK CONSTRAINT [FK_Donhang_Nguoidung]
GO
ALTER TABLE [dbo].[DonhangChitiet]  WITH CHECK ADD  CONSTRAINT [FK_DonhangChitiet_Donhang] FOREIGN KEY([mahd])
REFERENCES [dbo].[Donhang] ([mahd])
GO
ALTER TABLE [dbo].[DonhangChitiet] CHECK CONSTRAINT [FK_DonhangChitiet_Donhang]
GO
ALTER TABLE [dbo].[DonhangChitiet]  WITH CHECK ADD  CONSTRAINT [FK_DonhangChitiet_KinhmatSKU] FOREIGN KEY([maSKU])
REFERENCES [dbo].[KinhmatSKU] ([idSKU])
GO
ALTER TABLE [dbo].[DonhangChitiet] CHECK CONSTRAINT [FK_DonhangChitiet_KinhmatSKU]
GO
ALTER TABLE [dbo].[Kinhmat]  WITH CHECK ADD  CONSTRAINT [FK_Kinhmat_Danhmuc] FOREIGN KEY([madanhmuc])
REFERENCES [dbo].[Danhmuc] ([id])
GO
ALTER TABLE [dbo].[Kinhmat] CHECK CONSTRAINT [FK_Kinhmat_Danhmuc]
GO
ALTER TABLE [dbo].[KinhmatSKU]  WITH CHECK ADD  CONSTRAINT [FK_KinhmatSKU_Kinhmat] FOREIGN KEY([masp])
REFERENCES [dbo].[Kinhmat] ([id])
GO
ALTER TABLE [dbo].[KinhmatSKU] CHECK CONSTRAINT [FK_KinhmatSKU_Kinhmat]
GO
ALTER TABLE [dbo].[Thanhtoan]  WITH CHECK ADD  CONSTRAINT [FK_Thanhtoan_Donhang] FOREIGN KEY([mahd])
REFERENCES [dbo].[Donhang] ([mahd])
GO
ALTER TABLE [dbo].[Thanhtoan] CHECK CONSTRAINT [FK_Thanhtoan_Donhang]
GO
ALTER TABLE [dbo].[Thongtinvanchuyen]  WITH CHECK ADD  CONSTRAINT [FK_Thongtinvanchuyen_Donhang] FOREIGN KEY([mahd])
REFERENCES [dbo].[Donhang] ([mahd])
GO
ALTER TABLE [dbo].[Thongtinvanchuyen] CHECK CONSTRAINT [FK_Thongtinvanchuyen_Donhang]
GO
USE [master]
GO
ALTER DATABASE [API_Kinhmat] SET  READ_WRITE 
GO
